"""add_notice_fields

Revision ID: 25384601487e
Revises: 
Create Date: 2026-07-11 11:20:49.574298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25384601487e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_public')
        batch_op.drop_column('importance')

    # ### end Alembic commands ###
