"""add batch audit fields

Revision ID: 698ec45b7c8c
Revises: 8638197ee39e
Create Date: 2026-08-14 16:43:12.867872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698ec45b7c8c'
down_revision = '8638197ee39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('audit_status', sa.String(length=16), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('audit_comment', sa.String(length=256), nullable=True, server_default=''))
        batch_op.create_foreign_key('fk_exam_batch_department_id', 'department', ['department_id'], ['id'])
        batch_op.create_foreign_key('fk_exam_batch_created_by', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_batch', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exam_batch_department_id', type_='foreignkey')
        batch_op.drop_constraint('fk_exam_batch_created_by', type_='foreignkey')
        batch_op.drop_column('audit_comment')
        batch_op.drop_column('audit_status')
        batch_op.drop_column('created_by')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
